stripe/react-connect-js

package.json
yarn.lock

Reference the published npm package instead of yalc

Use connect-js npm package

---

README.md
package.json
src/Components.tsx
yarn.lock

There were a few components exposed in this SDK that aren't yet part of our public beta. This PR removes these components.

Remove components that aren't in the public beta

---

src/Components.tsx

Removing components that are only available in beta

Remove beta components

---

package.json
rollup.config.js
src/useCreateComponent.tsx
yarn.lock

Changes from
https://github.com/stripe/react-connect-js/pull/33
https://github.com/stripe/react-connect-js/pull/34
https://github.com/stripe/react-connect-js/pull/35

Update beta branch from master

---

.github/workflows/test.yml
package.json

This PR adds CI validation
Sample run: https://github.com/stripe/react-connect-js/actions/runs/6962014980/job/18944839128?pr=55

Add CI validation to react-connect-test (beta)

---

.github/workflows/test.yml
package.json

This PR adds CI validation for this repo
Sample run (For this branch): https://github.com/stripe/react-connect-js/actions/runs/6961878692/job/18944411518

Add CI validation

---

package.json
src/Components.tsx
src/types.ts
src/utils/useUpdateWithSetter.ts
yarn.lock

Utilizes the changes made in https://github.com/stripe/connect-js/pull/87 to get ephemeral function working

Add setters for fetch ephemeral key function

---

README.md

issue brought up by: [RUN_CAUI-1140](https://jira.corp.stripe.com/browse/RUN_CAUI-1140)

update connect initialization in readme

---

package.json
src/Components.tsx
yarn.lock

Adds documents component to beta
https://jira.corp.stripe.com/browse/CAUI-1839

Add documents component (beta)

---

package.json
src/Components.tsx
yarn.lock

Adds documents component 
https://jira.corp.stripe.com/browse/CAUI-1839

Add documents component

---

package.json
yarn.lock

related to https://github.com/stripe/connect-js/pull/95/files

add rollup to dev dependencies

---

README.md
package.json
src/Components.tsx
yarn.lock

add collectionOptions prop to account management and update connect-js version

add collectionOptions prop to account management, update connect-js version

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Add account management and notification banner

---

package.json
src/Components.tsx
yarn.lock

Add Payouts List and Balances

---

package.json
src/Components.tsx

Add `tax-registrations` and `tax-settings` components.

[Beta] Add tax components for beta

---

package.json
src/Components.tsx
yarn.lock

Adds collectionOptions support to the Notification Banner.

Add collectionOptions to Notification Banner

---

package.json
src/Components.tsx
yarn.lock

Adds onNotificationsChange callback to react-connect.js
Bumping connect js to 3.3.7

Added onNotificationsChange

---

package.json
src/Components.tsx
yarn.lock

Mirror to changes made on #95. Adds onNotificationsChange to Notification Banner and bumps connect js version.

Added OnNotificationsChange + connectjs bump

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Adding payload to onNotificationsChange

update onNotificationsChange to include payload

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Mirror to https://github.com/stripe/react-connect-js/pull/98

Updated onNotificationChange to include payload beta

---

package.json
src/Components.tsx
yarn.lock

Adds new tax components.
connect-js PR: https://github.com/stripe/connect-js/pull/139
https://jira.corp.stripe.com/browse/TAXCONNECT-744

Add new tax components

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Add load event handlers, common component props and bump @stripe/connect-js to 3.3.14-beta-1

Add load events and common props type

---

src/Components.tsx

Follow up to https://github.com/stripe/connect-js/pull/152
Adds new Capital components and their params. 
API review: https://docs.google.com/document/d/1UOfEiV031A8ml3dJJNaHjdZs3PAMp0B0zCmgj4Hk2P0/edit
Setters defined: 
https://livegrep.corp.stripe.com/view/stripe-internal/pay-server/frontend/connect/submerchant-surfaces/src/connect/ConnectJSInterface/ConnectElementDefinitions/capital-financing.ts#L44
https://livegrep.corp.stripe.com/view/stripe-internal/pay-server/frontend/connect/submerchant-surfaces/src/connect/ConnectJSInterface/ConnectElementDefinitions/capital-financing-promotion.ts
https://livegrep.corp.stripe.com/view/stripe-internal/pay-server/frontend/connect/submerchant-surfaces/src/connect/ConnectJSInterface/ConnectElementDefinitions/capital-financing-application.ts

Add capital beta components

---

package.json
src/Components.tsx
src/types.ts
src/utils/useUpdateWithSetter.ts
yarn.lock

Follow-up from https://github.com/stripe/connect-js/pull/158/files
API Review: https://docs.google.com/document/d/1UOfEiV031A8ml3dJJNaHjdZs3PAMp0B0zCmgj4Hk2P0/edit#heading=h.1akuxbx59euz

Update capital financing promotion params

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Same as https://github.com/stripe/react-connect-js/pull/118 but for preview

Updated connect.js version and added StepChange to account onboarding

---

package.json
src/Components.tsx
yarn.lock

Follow up from https://github.com/stripe/connect-js/pull/164
Adding new props from the recently completed [api review addendum](https://docs.google.com/document/d/1UOfEiV031A8ml3dJJNaHjdZs3PAMp0B0zCmgj4Hk2P0/edit#bookmark=id.blg5ihxorla3)

Add capital component link customization props

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Depends on https://github.com/stripe/connect-js/pull/165.
API review: https://docs.google.com/document/d/1jBeWgOml1s6Pk0zwN323j96_RcqvFYqCX-4zBfJqWVw/edit

Expose new Tax components props

---

.github/dependabot.yml

Ssame as https://github.com/stripe/connect-js/pull/183

Add dependabot file 

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Add `setDefaultFilters` setter and related types to Payments component.

Add default filter setter to Payments

---

package.json

The referenced peer dependency does not exist. Updating this.

Fix peer dependency

---

package.json
src/Components.test.ts
yarn.lock

Same like this: https://github.com/stripe/react-connect-js/pull/133 - This time only applied to the `preview` branch.
@jorgea-stripe, feel free to merge directly

Add test for component name to start with `Connect` for the embedded components

---

src/Components.tsx

This adds the issuingProgram prop to the IssuingCardsList component that was added to connect-js in https://github.com/stripe/connect-js/pull/178

Add issuingProgram prop to the IssuingCardsList program

---

package.json
src/Components.tsx
src/types.ts
src/utils/useUpdateWithSetter.ts
yarn.lock

These components are being GA'd. Code was copied directly from the `preview` branch.

Add Issuing/Treasury components

---

src/Components.tsx

Add tax threshold monitoring

---

package.json
src/Components.tsx
yarn.lock

add payment disputes and disputes list to ga react sdk

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Adds IP Promo component for GA
Tested with a local version and confirmed setters are called as expected:
https://github.com/user-attachments/assets/a38cd91c-6aa7-408a-9cad-101ae48b694e

Add IP Promotion component (ga)

---

package.json

upgrade preview to 3.3.35-preview-1

v3.3.35-preview-1
