src/utils/useAttachAttribute.ts

Previously we were checking `&& value` which would cause the attributes not to update on false values. Instead the check should be making sure the value is not undefined

Fix adding attributes on components

---

src/Components.tsx
src/index.ts
src/useCreateComponent.tsx
src/utils/useAttachEvent.ts
tsconfig.json

This adds the transactions components. Also exports the methods to add attributes and event listeners to the components. I noticed there would be an issue since the HTML element is not returned directly from the wrappers, so I also exported the `useCreateComponent` method which would allow developers to create an instance of a wrapper and also have access to the html element to add attributes/events to.
Also changes target output to es6.

Add transactions component and expose attributes methods

---

.eslintrc.yml
examples/components.jsx
src/ConnectComponents.tsx
src/useCreateComponent.tsx

This brings us more inline with react-stripe-js which takes a Promise which is the result of initializing the stripe-js library. We also take a resolved connectInstance or null. This is backwards compatible and flexible enough to support many different initialization patterns. 
This is useful because we have a pattern that stripe-js does not have: namely, allowing multiple initializations of connect-js. 
Both cases will probably have users load the connectJs script at the top level of their app, but depending on whether a consumer also creates a single connectInstance or intends to creates multiple connectInstances will determine whether they need to wait for the promise to resolve at the time that they render the ConnectComponentsProvider.

Accept null or a promise for the ConnectComponentsProvider and only render once the connectInstance is present

---

package.json
yarn.lock

This bumps React version from 18 to 16.8 (when hooks are first supported)
Tested on quickstart apps using both React 18 and 16

Bump React version down to 16 for wider support

---

package.json

Hi!
I had the same problem as described in #28. The problem I found is that it only limits to semver of React 16 which is not working with projects that are using React 17 or 18. To solve this I changed the version to be greater than or equal to 16.8.0 (which I think is chosen because this is the first version with hooks). Besides React's version, I'm also using beta connect components which with the current peer dependencies are also not supported, so I propose adding `|| ^2.0.1-beta.1` to solve this problem.
Hope this is helpful and can be merged. Let me know if I can help this PR to be merged and I would be more than happy to make further changes

#28 Allow newer version of React.js and beta of `@stripe/connect-js`

---

package.json

Noticed that stripe-connect-js was moved to devdependencies instead of peerdependencies

Move stripe-connect-js to peer dependencies

---

package.json
rollup.config.js
src/useCreateComponent.tsx
yarn.lock

This PR makes use of rollup to get the package.json version in the code, removing the need for parsing the package.json file (which was causing problems for some TS integrations with `resolveJsonModules: false`).
With these updates:
1. The version is included
2. The package.json file is no longer in shared.ts

Remove the need for JSON parsing (resolveJsonModules in tsconfig)

---

src/utils/useAttachAttribute.ts

Today the react SDK is never removing HTML attributes, even when setting a prop to `undefined`. This can be a problem when explicitly setting a prop to `undefined` - this PR fixes it by calling `removeAttribute` when the prop is set to undefined.
https://github.com/stripe/react-connect-js/assets/95381655/4239fbcc-0862-4619-8e4d-7846b1b3e7c4

Setting a prop to undefined should remove the HTML attribute

---

package.json
src/Components.tsx

~Depends on https://github.com/stripe/connect-js/pull/51.~ 
This adds the ConnectPaymentMethodSettings component (currently in private beta). I also updated the package dependencies to require `"@stripe/connect-js": "2.0.1-beta.5"` which adds the underlying enum value.

Add ConnectPaymentMethodSettings component for beta access

---

src/useCreateComponent.tsx

These 2 were missing and were causing changes to the context to not re-create components.

Add correct dependencies to create useEffect

---

src/useCreateComponent.tsx

These 2 were missing and were causing changes to the context to not re-create components.

Add the correct dependencies to the create useEffect

---

src/useCreateComponent.tsx

We need to move the analytics to the component since the connector might not be initialized when the component is created

Set reactsdk version on the component instead of connector

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Adds support for Issuing Card and Issuing Cards List plus setter methods. 
Also implements `useUpdateWithSetter` that's also going into `master` in #52.

Add Issuing Card and Issuing Cards List wrappers

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Adds `collectionOptions` to support collecting future requirements using the API aligned on:
```
collectionOptions?: {
fields: 'currently_due' | 'eventually_due',
futureRequirements?: 'omit' | 'include' // Default to `omit`
}
```

Adds collectionOptions to ConnectAccountOnboarding

---

package.json

A previous PR https://github.com/stripe/react-connect-js/pull/63 missed a devDependencies update, so fixing that here

Require higher beta version of connect.js in devDependencies

---

package.json

A previous PR https://github.com/stripe/react-connect-js/pull/61 did not bump the `devDependencies`, so fixing that here

Require an updated verison of connect-js

---

src/index.ts

Consumers aren't able to use the `useUpdateWithSetter` utility hook, this exports it so that it is available.

Expose the useUpdateWithSetter utility for consumers to use

---

src/index.ts

Applies the same change as https://github.com/stripe/react-connect-js/pull/67 on the `beta` branch

Expose the useUpdateWithSetter utility for consumers to use (#67)

---

README.md
examples/components.jsx

- Removes `visible` prop in the example and README files since this prop is no longer supported
- Also updates the `chargeId` prop to `payment` in the aforementioned files
- Update example code to use loadConnectAndInitialize

Remove visible prop in PaymentDetails component example

---

README.md
examples/components.jsx
src/Components.tsx

- Removes `visible` prop from PaymentDetails component that is no longer supported, from the README and the example code
- Changes `chargeId` prop in PaymentDetails component to use `payments`
- Updates example code to use `loadConnectAndInitialize`

[Beta] Remove visible prop and update example code/README

---

package.json
yarn.lock

related to https://github.com/stripe/connect-js/pull/95/files
fixes issue w/ yarn build not running

Add rollup to dev dependencies (beta)

---

src/useCreateComponent.tsx

Connect embedded components advertise they would take the full width of the page: https://docs.corp.stripe.com/connect/get-started-connect-embedded-components#width-and-height. However this isn't always true, specifically if you do:
```
<style>
.content {
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
text-align: center;
width: 420px;
padding-top: 40px;
margin-bottom: 110px;
}
</style>
<div class="content">
<ConnectOnboarding />
</div>
```
The width of ConnectOnboarding would be as small as possible (320px!).
This breaks the advertised 100% width promise, and results in a very narrow UI:
This also repro's for other components:
With this fix, the wrapper div takes the full width, allowing the custom element to also take the full width:
Onboarding: …

Set the width of the wrapper div to 100% to preserve the "full width" expectation of embedded components

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

API Review: https://docs.google.com/document/d/1WSZBpaLvJLDmhaA3VMTpV3cYvaZ920gWDBNX0dKMXrA/edit#heading=h.nbrl5773k5jx
connect-js changes: https://github.com/stripe/connect-js/pull/137
Tested on connect-test

Add App components

---

src/Components.tsx

Fixes https://github.com/stripe/react-connect-js/issues/107
Before:
After:

Make onLoaderStart and onLoadError optional

---

package.json
src/Components.tsx
yarn.lock

Added to ConnectJS here: https://github.com/stripe/connect-js/pull/145
It's only blocked by needing a new connect-js `beta` release to be cut. In this PR, I've optimistically updated the package.json to use the anticipated next version of `connect-js@beta` once it's released.

Add paymentMethodConfiguration property to the ConnectPaymentMethodSettings component

---

package.json
src/Components.tsx
yarn.lock

We'll be removing the card art file link setters, so we need to update the React wrappers appropriately. Updated the package.json file to the latest connect-js beta version that includes https://github.com/stripe/connect-js/pull/156 and the yarn.lock file.

Remove card art file link setters from Issuing ECs

---

.github/workflows/test.yml
README.md

Removes use of beta in favor of preview
In the README,  updated the link re: preview access.

Remove 'beta' in favor of 'preview'

---

package.json
src/Components.tsx
yarn.lock

This adds the showSpendControls to the IssuingCard and IssuingCardsList components and bumps the connect-js dependency version to the latest that includes the changes from https://github.com/stripe/connect-js/pull/162.

Add showSpendControls prop to the IssuingCard and IssuingCardsList components

---

package.json
src/Components.tsx
yarn.lock

Follow up to https://github.com/stripe/connect-js/pull/182
Renames the `faqUrl` parameter to `howCapitalWorksUrl` to be consistent with the other Capital components per the latest [API review addendum](https://docs.google.com/document/d/1UOfEiV031A8ml3dJJNaHjdZs3PAMp0B0zCmgj4Hk2P0/edit?tab=t.0#bookmark=id.bwp66tafe1n3)
Note that this is a _breaking_ change but the component is not used by any external platforms

Rename CapitalFinancing faqUrl parameter

---

src/utils/useUpdateWithSetter.ts

A setter can fail on invalid values, and it can also fail when it is not defined. We want to avoid causing the entire react tree to fail rendering.

Update useUpdateWithSetter to not cause a react render loop when the setter fails

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

Same changes as #135. Add `setDefaultFilters` setter and related types to Payments component, and update the connect.js version.

Add default filters setter and update connect.js version

---

package.json
src/Components.tsx
src/types.ts
yarn.lock

Follow up to https://github.com/stripe/connect-js/pull/193
Adds a new field, `activeFinancingCount` to the data payload for the `setOnEligibleFinancingOfferLoaded` in the CapitalFinancingPromotion component so that platforms are able to selectively hide the component if the connected account has active financing.

Add activeFinancingCount to setOnEligibleFinancingOfferLoaded payload in CapitalFinancingPromotion component

---

src/utils/useAttachAttribute.ts
src/utils/useAttachEvent.ts

These 2 methods should no longer be used. We should be using setters only. These are still used in a few instances unfortunately, so I am marking them as deprecated to avoid breaks.

Mark the use of attributes and events as deprecated (use setters instead)

---

package.json
src/Components.tsx
src/utils/useUpdateWithSetter.ts
yarn.lock

This adds the Product Tax Code (PTC) Selector component to the preview branch.

Add the Product Tax Code (PTC) Selector component

---

package.json
src/Components.tsx
yarn.lock

Add export-tax-transactions Embedded Component to Preview.

Add export-tax-transactions Embedded Component to Preview

---

package.json
src/Components.tsx
yarn.lock

Tested with yalc that it works and has typing support

add payment disputes to preview

---

src/useCreateComponent.tsx

This will let us determine the heights that flexible components should stretch to.

Add a data attribute to npm wrapper divs so we can identify them from connect-js internally

---

package.json
src/Components.tsx
yarn.lock

- Bumps `@stripe/connect-js` version to `"3.3.36-preview-1"
- Adds `onApplicationStepChange` prop to `ConnectCapitalFinancingApplication` and `ConnectCapitalFinancingPromotion`
Tested by rendering component and listening for event using local build:
Result:
https://github.com/user-attachments/assets/9750b30e-d435-477f-bd2a-4c48f12234ff

Add onApplicationStepChange to Capital Financing Application and Promotion Components
